export const ACTION_TYPE = {
  SET_RECIPE_DATA: 'SET_RECIPE_DATA',
  RESET_RECIPE_DATA: 'RESET_RECIPE_DATA',
  SET_POST_DATA: 'SET_POST_DATA',
  RESET_POST_DATA: 'RESET_POST_DATA',
  LOGIN_USER: 'LOGIN_USER',
  REGISTER_USER: 'REGISTER_USER',
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT',
  UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
};
